name: my_first_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  audioplayers: ^6.1.0
  file_picker: ^8.1.7
  shared_preferences: ^2.2.2
  audio_session: ^0.1.18

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
